"""
Learning curve analysis for the compliant base outreach project.

Goal:
Evaluate how the Gaussian Process performance changes when the number
of training samples increases.

This helps justify the dataset size used in the project.
"""

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import ConstantKernel, Matern, WhiteKernel
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


warnings.filterwarnings("ignore")


DATA_PATH = "data/dataset_outreach.csv"
RESULTS_DIR = "results"
FIGURES_DIR = "figures"

PARAM_COLS = [
    "Kb",
    "Kr",
    "Mb",
    "hb",
    "hr",
    "f0",
    "f1",
    "A",
    "x_r_start",
]

TARGET_COL = "peak_y"


def load_dataset():
    """
    Load dataset generated by src/dataset.py.
    """
    if not os.path.exists(DATA_PATH):
        raise FileNotFoundError(f"Dataset not found: {DATA_PATH}")

    df = pd.read_csv(DATA_PATH, comment="#")

    missing_cols = [c for c in PARAM_COLS + [TARGET_COL] if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing columns in dataset: {missing_cols}")

    X = df[PARAM_COLS].values
    y = df[TARGET_COL].values

    return X, y, df


def train_gp(X_train, y_train):
    """
    Train a Gaussian Process model with the same logic used in the project.
    """

    scaler_X = StandardScaler()
    scaler_y = StandardScaler()

    X_train_scaled = scaler_X.fit_transform(X_train)
    y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()

    kernel = (
        ConstantKernel(1.0, (1e-3, 1e3))
        * Matern(
            length_scale=np.ones(X_train.shape[1]),
            length_scale_bounds=(1e-2, 1e3),
            nu=2.5,
        )
        + WhiteKernel(noise_level=1e-5, noise_level_bounds=(1e-8, 1e-1))
    )

    gp = GaussianProcessRegressor(
        kernel=kernel,
        alpha=1e-8,
        normalize_y=False,
        n_restarts_optimizer=2,
        random_state=42,
    )

    gp.fit(X_train_scaled, y_train_scaled)

    return gp, scaler_X, scaler_y


def evaluate_gp(gp, scaler_X, scaler_y, X_test, y_test):
    """
    Evaluate GP on a fixed test set.
    """

    X_test_scaled = scaler_X.transform(X_test)

    y_pred_scaled, y_std_scaled = gp.predict(X_test_scaled, return_std=True)

    y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()

    r2 = r2_score(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)

    return r2, rmse, mae


def run_learning_curve():
    """
    Run learning curve using increasing training set sizes.
    """

    os.makedirs(RESULTS_DIR, exist_ok=True)
    os.makedirs(FIGURES_DIR, exist_ok=True)

    X, y, df = load_dataset()

    print("=" * 70)
    print("LEARNING CURVE ANALYSIS")
    print("=" * 70)
    print(f"Dataset loaded: {DATA_PATH}")
    print(f"Total samples: {len(df)}")

    # Fixed test set for fair comparison
    X_pool, X_test, y_pool, y_test = train_test_split(
        X,
        y,
        test_size=0.20,
        random_state=42,
    )

    print(f"Training pool samples: {len(X_pool)}")
    print(f"Fixed test samples: {len(X_test)}")

    # Maximum training size is the training pool size
    train_sizes = [20, 40, 60, 80, 100, 130, 150, len(X_pool)]

    # Remove possible duplicates
    train_sizes = sorted(list(set(train_sizes)))

    n_repeats = 3

    all_results = []

    for n_train in train_sizes:
        print("\n" + "-" * 70)
        print(f"Training size: {n_train}")

        r2_list = []
        rmse_list = []
        mae_list = []

        for repeat in range(n_repeats):
            rng = np.random.default_rng(seed=100 + repeat)

            subset_idx = rng.choice(len(X_pool), size=n_train, replace=False)

            X_train = X_pool[subset_idx]
            y_train = y_pool[subset_idx]

            gp, scaler_X, scaler_y = train_gp(X_train, y_train)

            r2, rmse, mae = evaluate_gp(
                gp,
                scaler_X,
                scaler_y,
                X_test,
                y_test,
            )

            r2_list.append(r2)
            rmse_list.append(rmse)
            mae_list.append(mae)

            print(
                f"  Repeat {repeat + 1}/{n_repeats} | "
                f"R²={r2:.4f}, RMSE={rmse:.5f} m, MAE={mae:.5f} m"
            )

        result = {
            "n_train": n_train,
            "r2_mean": np.mean(r2_list),
            "r2_std": np.std(r2_list),
            "rmse_mean": np.mean(rmse_list),
            "rmse_std": np.std(rmse_list),
            "mae_mean": np.mean(mae_list),
            "mae_std": np.std(mae_list),
        }

        all_results.append(result)

        print(
            f"Mean result | "
            f"R²={result['r2_mean']:.4f} ± {result['r2_std']:.4f}, "
            f"RMSE={result['rmse_mean']:.5f} ± {result['rmse_std']:.5f} m"
        )

    results_df = pd.DataFrame(all_results)

    csv_path = os.path.join(RESULTS_DIR, "learning_curve_results.csv")
    results_df.to_csv(csv_path, index=False)

    print("\n" + "=" * 70)
    print("LEARNING CURVE RESULTS")
    print("=" * 70)
    print(results_df)
    print(f"\nSaved CSV: {csv_path}")

    plot_learning_curve(results_df)

    print("\nLearning curve completed.")


def plot_learning_curve(results_df):
    """
    Plot learning curve with R² and RMSE.
    """

    fig, ax1 = plt.subplots(figsize=(10, 6))

    x = results_df["n_train"].values

    r2_mean = results_df["r2_mean"].values
    r2_std = results_df["r2_std"].values

    rmse_mean = results_df["rmse_mean"].values
    rmse_std = results_df["rmse_std"].values

    # R² axis
    ax1.errorbar(
        x,
        r2_mean,
        yerr=r2_std,
        marker="o",
        linewidth=2,
        capsize=4,
        label="Test R²",
    )

    ax1.set_xlabel("Number of training samples", fontsize=12)
    ax1.set_ylabel("Test R²", fontsize=12)
    ax1.set_ylim(0.0, 1.05)
    ax1.grid(True, alpha=0.3)

    # RMSE axis
    ax2 = ax1.twinx()

    ax2.errorbar(
        x,
        rmse_mean * 1000,
        yerr=rmse_std * 1000,
        marker="s",
        linewidth=2,
        capsize=4,
        linestyle="--",
        label="Test RMSE",
    )

    ax2.set_ylabel("Test RMSE [mm]", fontsize=12)

    # Reference final dataset size
    ax1.axvline(
        x=max(x),
        linestyle=":",
        linewidth=2,
        label=f"Final training size = {max(x)}",
    )

    plt.title(
        "Learning Curve: Effect of Training Set Size on GP Performance",
        fontsize=14,
        fontweight="bold",
    )

    # Combined legend
    lines_1, labels_1 = ax1.get_legend_handles_labels()
    lines_2, labels_2 = ax2.get_legend_handles_labels()

    ax1.legend(
        lines_1 + lines_2,
        labels_1 + labels_2,
        loc="lower right",
    )

    plt.tight_layout()

    fig_path = os.path.join(FIGURES_DIR, "learning_curve.png")
    plt.savefig(fig_path, dpi=300, bbox_inches="tight")
    plt.close()

    print(f"Saved plot: {fig_path}")


if __name__ == "__main__":
    run_learning_curve()